.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. mazacoin_qt test_mazacoin_qt
clean: FORCE
	$(MAKE) -C .. mazacoin_qt_clean test_mazacoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_mazacoin_qt_check
mazacoin-qt mazacoin-qt.exe: FORCE
	 $(MAKE) -C .. mazacoin_qt
